apiVersion: v1
kind: Secret
metadata:
  name: myrocket-mongodb
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: myrocket
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: "dGVzdFBBU1Nyb290"
  mongodb-passwords: "dGVzdFBBU1M="
  mongodb-replica-set-key: "VGJNZTJiZ1pjVA=="
